name: Run Tests

on: [pull_request, push]

permissions:
  contents: write

env:
  LITELLM_API_KEY: ${{ secrets.LITELLM_API_KEY }}

jobs:
  run_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --dev --all-extras

      - name: Run tests
        run: uv run pytest tests -vv
