name: Security Checker

on: [pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install dependencies
        run: uv pip install bandit

      - name: Run Bandit
        run: uv run bandit -c pyproject.toml -r src/ -ll
